### ISSUE TITLE
Gerenciamento de Usuários

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-web-old#22]
# História de Usuário
O administrador precisa de uma tela para gerenciar os usuários cadastrados na plataforma.

# Resumo
Criar uma nova tela para gerenciamentos dos usuários. As funcionalidades da tela estarão divididas nas issues abaixo, sendo a primeira (Listar Usuários) a principal (por conter a task de criação da tela e exibição da tabela).

# Critérios de Aceite

- [ ] Criar Tela **e** Listar Usuários (#23)
- [ ] Filtrar+Ordenar (#24)
- [ ] Adicionar Usuário (—)
- [ ] Remover Usuário (—)
- [ ] Editar Usuário (—)
  - [ ] Detalhes do Usuário (—)
  - [ ] Editar Perfil do Usuário (—)
  - [ ] Editar Complemento de Dados (—)
  - [ ] Editar Formulário Socioeconomico (—)
- [ ] Resetar Senha (—)

# Protótipo

#7 

# Informações Adicionais

—
